#include ".\md4c\src\entity.h"
#include ".\md4c\src\md4c-html.h"
#include ".\md4c\src\md4c.h"
#include <QApplication>
#include <QMainWindow>
#include "ui_mainwindow.h"
#include "json\single_include\nlohmann\json.hpp"
#include <iostream>
#include <thread>
#include <string>
#include <ctsdlib>
#include <fstream>